import { Activity, Accessibility, Ambulance, Baby, Bone, Brain, CircleDot, Dumbbell, Ear, Eye, FlaskConical, HandHeart, HeartPulse, Microscope, Pill, Puzzle, Radiation, ScanLine, Scissors, ShieldCheck, Smile, Stethoscope, Syringe, Waves } from "lucide-react";
import { specialties } from "@/data/specialties";
import Link from "next/link";
import { Container } from "@/components/ui/Container";
import { SectionHeading } from "@/components/ui/SectionHeading";

const specialtyIcons = { Urology: Waves, Cardiology: HeartPulse, "Urgent Care": Ambulance, "Laboratory Billing": FlaskConical, "Behavioral Health": Brain, Orthopedics: Bone, "ABA Therapy": Puzzle, DME: Accessibility, "Sports Medicine": Dumbbell, Pediatrics: Baby, Anesthesia: Syringe, "Family Medicine": HandHeart, "Oral and Maxillofacial Surgery": Smile, "General Practice": Stethoscope, Chiropractic: Activity, Dermatology: CircleDot, Podiatry: ScanLine, Endocrinology: Pill, "Osteopathic Medicine": Bone, Surgery: Scissors, "Internal Medicine": Stethoscope, "Occupational Therapy": Accessibility, "Vascular Surgery": Activity, "Speech Therapy": Ear, "Physical Therapy": Dumbbell, Psychiatry: Brain, Radiology: Radiation, "Plastic Surgery": Scissors, Physiotherapy: Accessibility, NEMT: Ambulance, Pathology: Microscope, "Emergency Medicine": Ambulance, "Pain Management": Activity, Ophthalmology: Eye, Gastroenterology: CircleDot, Oncology: Radiation, Neurology: Brain, Neonatology: Baby, "Mental Health": Brain, "Infectious Disease": ShieldCheck, Hepatology: CircleDot, Hematology: FlaskConical, Geriatrics: HandHeart, ENT: Ear, Otolaryngology: Ear, Dentistry: Smile } as const;

export function Specialties({ preview = false }: { preview?: boolean }) {
  return <section id="specialties" className="section specialties-section scroll-mt-20"><Container><SectionHeading eyebrow="Practice Types" title="Medical Specialties" description="Explore the specialties currently represented in the MD Claims directory." /><div className="specialties-grid mx-auto mt-12 max-w-6xl">{(preview ? specialties.slice(0, 6) : specialties).map((specialty) => { const Icon = specialtyIcons[specialty] ?? Stethoscope; return <button type="button" key={specialty} className="specialty-card specialty-flip group"><span className="specialty-flip-inner"><span className="specialty-card-face specialty-card-front"><Icon aria-hidden="true" />{specialty}</span><span className="specialty-card-face specialty-card-back">{specialty} billing support designed around your practice workflow.</span></span></button>; })}</div>{preview && <div className="mt-10 text-center"><Link href="/md-claims/specialties/" className="button button-primary">View all specialties</Link></div>}</Container></section>;
}

